title: pusu's blog
author: pusu
description: >- # this means to ignore newlines until "baseurl:"
  欢迎来到蒲素的博客，这里是我的写作自留地。
baseurl: "" # since you are using a custom domain, you can leave this empty
url: "https://www.pusu.life" # use your custom domain here

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true
