title: pusu's blog
author: pusu
description: >- # this means to ignore newlines until "baseurl:"
  欢迎来到蒲素的博客，这里是我的写作自留地。

theme: jekyll-theme-minimal

# 选择 Mint 皮肤
minimal_mistakes_skin: "mint"
